const transpiler = require('d:/code/js/SimpleScriptCompiler/transpiler')
const fs = require('fs')

const chimpfiles = fs.readdirSync('.').filter(x => x.endsWith('.chimp'))

const note = '// Note: this file is generated by compile-all.js\n'
fs.writeFileSync('all-in-one.txt', note + chimpfiles.map(x => `include $/${x}`).join('\n'))

chimpfiles.push('all-in-one.txt')

chimpfiles.forEach(x => {
    const out = 'output/' + x.replace(/\.[^.]*$/, '.script')
    console.log(`transpiling ${x} to ${out}`)
    transpiler.transpile(x, out)
})
